# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oracle.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'oracle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0coracle.proto\x12\x06oracle\"\xd8\x01\n\nDLCRequest\x12\x14\n\x0clocal_pubkey\x18\x01 \x01(\t\x12\x12\n\nlocal_txid\x18\x02 \x01(\t\x12\x1a\n\x12local_fund_address\x18\x03 \x01(\t\x12\x1c\n\x14local_change_address\x18\x04 \x01(\t\x12\x15\n\rremote_pubkey\x18\x05 \x01(\t\x12\x13\n\x0bremote_txid\x18\x06 \x01(\t\x12\x1b\n\x13remote_fund_address\x18\x07 \x01(\t\x12\x1d\n\x15remote_change_address\x18\x08 \x01(\t\"k\n\x08\x44LCReply\x12\x0f\n\x07\x63\x65t_txs\x18\x01 \x03(\t\x12\x0f\n\x07\x66und_tx\x18\x02 \x01(\t\x12\x11\n\trefund_tx\x18\x03 \x01(\t\x12\x10\n\x08r_values\x18\x04 \x03(\t\x12\x18\n\x10outcome_messages\x18\x05 \x03(\t28\n\x03\x44LC\x12\x31\n\tCreateDLC\x12\x12.oracle.DLCRequest\x1a\x10.oracle.DLCReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oracle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DLCREQUEST']._serialized_start=25
  _globals['_DLCREQUEST']._serialized_end=241
  _globals['_DLCREPLY']._serialized_start=243
  _globals['_DLCREPLY']._serialized_end=350
  _globals['_DLC']._serialized_start=352
  _globals['_DLC']._serialized_end=408
# @@protoc_insertion_point(module_scope)
