// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: oracle.proto
#ifndef GRPC_oracle_2eproto__INCLUDED
#define GRPC_oracle_2eproto__INCLUDED

#include "oracle.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace oracle {

class DLC final {
 public:
  static constexpr char const* service_full_name() {
    return "oracle.DLC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CreateDLC(::grpc::ClientContext* context, const ::oracle::DLCRequest& request, ::oracle::DLCReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::oracle::DLCReply>> AsyncCreateDLC(::grpc::ClientContext* context, const ::oracle::DLCRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::oracle::DLCReply>>(AsyncCreateDLCRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::oracle::DLCReply>> PrepareAsyncCreateDLC(::grpc::ClientContext* context, const ::oracle::DLCRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::oracle::DLCReply>>(PrepareAsyncCreateDLCRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CreateDLC(::grpc::ClientContext* context, const ::oracle::DLCRequest* request, ::oracle::DLCReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateDLC(::grpc::ClientContext* context, const ::oracle::DLCRequest* request, ::oracle::DLCReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::oracle::DLCReply>* AsyncCreateDLCRaw(::grpc::ClientContext* context, const ::oracle::DLCRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::oracle::DLCReply>* PrepareAsyncCreateDLCRaw(::grpc::ClientContext* context, const ::oracle::DLCRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreateDLC(::grpc::ClientContext* context, const ::oracle::DLCRequest& request, ::oracle::DLCReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::oracle::DLCReply>> AsyncCreateDLC(::grpc::ClientContext* context, const ::oracle::DLCRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::oracle::DLCReply>>(AsyncCreateDLCRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::oracle::DLCReply>> PrepareAsyncCreateDLC(::grpc::ClientContext* context, const ::oracle::DLCRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::oracle::DLCReply>>(PrepareAsyncCreateDLCRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreateDLC(::grpc::ClientContext* context, const ::oracle::DLCRequest* request, ::oracle::DLCReply* response, std::function<void(::grpc::Status)>) override;
      void CreateDLC(::grpc::ClientContext* context, const ::oracle::DLCRequest* request, ::oracle::DLCReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::oracle::DLCReply>* AsyncCreateDLCRaw(::grpc::ClientContext* context, const ::oracle::DLCRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::oracle::DLCReply>* PrepareAsyncCreateDLCRaw(::grpc::ClientContext* context, const ::oracle::DLCRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateDLC_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CreateDLC(::grpc::ServerContext* context, const ::oracle::DLCRequest* request, ::oracle::DLCReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateDLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateDLC() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateDLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateDLC(::grpc::ServerContext* /*context*/, const ::oracle::DLCRequest* /*request*/, ::oracle::DLCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateDLC(::grpc::ServerContext* context, ::oracle::DLCRequest* request, ::grpc::ServerAsyncResponseWriter< ::oracle::DLCReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateDLC<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreateDLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateDLC() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::oracle::DLCRequest, ::oracle::DLCReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::oracle::DLCRequest* request, ::oracle::DLCReply* response) { return this->CreateDLC(context, request, response); }));}
    void SetMessageAllocatorFor_CreateDLC(
        ::grpc::MessageAllocator< ::oracle::DLCRequest, ::oracle::DLCReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::oracle::DLCRequest, ::oracle::DLCReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateDLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateDLC(::grpc::ServerContext* /*context*/, const ::oracle::DLCRequest* /*request*/, ::oracle::DLCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateDLC(
      ::grpc::CallbackServerContext* /*context*/, const ::oracle::DLCRequest* /*request*/, ::oracle::DLCReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreateDLC<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateDLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateDLC() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateDLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateDLC(::grpc::ServerContext* /*context*/, const ::oracle::DLCRequest* /*request*/, ::oracle::DLCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateDLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateDLC() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateDLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateDLC(::grpc::ServerContext* /*context*/, const ::oracle::DLCRequest* /*request*/, ::oracle::DLCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateDLC(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateDLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateDLC() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateDLC(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateDLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateDLC(::grpc::ServerContext* /*context*/, const ::oracle::DLCRequest* /*request*/, ::oracle::DLCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateDLC(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateDLC : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateDLC() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::oracle::DLCRequest, ::oracle::DLCReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::oracle::DLCRequest, ::oracle::DLCReply>* streamer) {
                       return this->StreamedCreateDLC(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateDLC() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateDLC(::grpc::ServerContext* /*context*/, const ::oracle::DLCRequest* /*request*/, ::oracle::DLCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateDLC(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::oracle::DLCRequest,::oracle::DLCReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateDLC<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateDLC<Service > StreamedService;
};

}  // namespace oracle


#endif  // GRPC_oracle_2eproto__INCLUDED
